[global]
  server string = SambaServer@Rpi5
  netbios name = RASPBERRYPI5
  idmap config * : range = 3000-7999
  security = user
  server min protocol = SMB2

  # disable printing services
  load printers = no
  printing = bsd
  printcap name = /dev/null
  disable spoolss = yes

[external_drive]
  comment = external drive@RPi5
  path = /mnt/external_drive
  browseable = yes
  read only = no
  writable = yes
  force user = pi
  create mask = 0660
  directory mask = 0770

[time_machine_hd]
  comment = time_machine_hd@RPi5
  path = /mnt/external_drive/time_machine_bck
  valid users = pi
  read only = no
  vfs objects = catia fruit streams_xattr
  fruit:time machine = yes
  fruit:time machine max size = 500G
