[*]
desktop_bg=#D6D3DE
desktop_shadow=#D6D3DE
desktop_fg=#E8E8E8
desktop_font=PibotoLt 12
wallpaper=/mnt/external_drive/nextcloud/nextcloud_data/data/<nextcloud-user>/files/Media/Pictures/background.jpg
wallpaper_mode=crop
show_documents=0
show_trash=1
show_mounts=1
folder=/home/pi/Desktop
