services:
  ddclient:
    image: lscr.io/linuxserver/ddclient:latest
    container_name: ddclient
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /mnt/external_drive/ddclient:/config
    restart: unless-stopped
    networks:
      - shared_network

networks:
  shared_network:
    external: true  